version: '3.8'
name: keycloak
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOG_LEVEL: DEBUG
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 12345
    command: start-dev --log-level DEBUG
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data:
    driver: local