--liquibase formatted sql
--changeset sayed:20240823_insert_client_statuses
INSERT INTO public.client_status (id, status, created_date, modified_date, created_by, modified_by, marked_as_deleted)
VALUES (nextval('client_status_id_sequence'), 'متابعة مكالمة', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'مهتم', current_timestamp, current_timestamp, 'system', 'system', false),
       (nextval('client_status_id_sequence'), 'معجبوش الكورس', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'حجز الكورس', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'الكورس التالي', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'خلص الزمالة', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'متابعة رسائل', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'الرقم غير صحيح', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('client_status_id_sequence'), 'الكورس غالى', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'التعريفية', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'غير مهتم', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('client_status_id_sequence'), 'اشترك في كورس اخر', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('client_status_id_sequence'), 'أخرى أذكرها', current_timestamp, current_timestamp, 'system', 'system',
        false);