--liquibase formatted sql
--changeset sayed:20240823_insert_referral_sources
INSERT INTO public.referral_source (id, source, created_date, modified_date, created_by, modified_by, marked_as_deleted)
VALUES (nextval('referral_source_id_sequence'), 'FB Paid', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('referral_source_id_sequence'), 'FB organic', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('referral_source_id_sequence'), 'Google', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('referral_source_id_sequence'), 'Website', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'Youtube', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'Telegram', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'registration', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('referral_source_id_sequence'), 'Friend', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'Email', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'SMS', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'Instagram', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'Confrance', current_timestamp, current_timestamp, 'system', 'system',
        false),
       (nextval('referral_source_id_sequence'), 'WhatsAPP Campign', current_timestamp, current_timestamp, 'system',
        'system',
        false),
       (nextval('referral_source_id_sequence'), 'B t B', current_timestamp, current_timestamp, 'system', 'system',
        false);